// Code generated by "makeops"; edit at your own risk.
package grammar

import (
	"git.sr.ht/~ionous/iffy/dl/composer"
)

// Action makes a parser scanner producing a script defined action.
type Action struct {
	Action string `if:"label=_"`
}

func (*Action) Compose() composer.Spec {
	return composer.Spec{
		Name: "action",
		Lede: "as",
	}
}

// Alias allows the user to refer to a noun by one or more other terms.
type Alias struct {
	Names  []string `if:"label=_"`
	AsNoun string   `if:"label=as_noun"`
}

func (*Alias) Compose() composer.Spec {
	return composer.Spec{
		Name: "alias",
	}
}

// AllOf makes a parser scanner
type AllOf struct {
	Series []ScannerMaker `if:"label=_"`
}

func (*AllOf) Compose() composer.Spec {
	return composer.Spec{
		Name: "all_of",
	}
}

// AnyOf makes a parser scanner
type AnyOf struct {
	Options []ScannerMaker `if:"label=_"`
}

func (*AnyOf) Compose() composer.Spec {
	return composer.Spec{
		Name: "any_of",
	}
}

// Directive starts a parser scanner
type Directive struct {
	Lede  []string       `if:"label=_"`
	Scans []ScannerMaker `if:"label=scans"`
}

func (*Directive) Compose() composer.Spec {
	return composer.Spec{
		Name: "directive",
	}
}

// Grammar Read what the player types and turn it into actions.
type Grammar struct {
	Grammar GrammarMaker `if:"label=_"`
}

func (*Grammar) Compose() composer.Spec {
	return composer.Spec{
		Name: "grammar",
	}
}

// Noun makes a parser scanner
type Noun struct {
	Kind string `if:"label=_"`
}

func (*Noun) Compose() composer.Spec {
	return composer.Spec{
		Name: "noun",
	}
}

// Retarget makes a parser scanner
type Retarget struct {
	Span []ScannerMaker `if:"label=_"`
}

func (*Retarget) Compose() composer.Spec {
	return composer.Spec{
		Name: "retarget",
	}
}

// Reverse makes a parser scanner
type Reverse struct {
	Reverses []ScannerMaker `if:"label=_"`
}

func (*Reverse) Compose() composer.Spec {
	return composer.Spec{
		Name: "reverse",
	}
}

// Self makes a parser scanner which matches the player. ( the player string is just to make the composer happy. )
type Self struct {
	Player string `if:"label=_"`
}

func (*Self) Compose() composer.Spec {
	return composer.Spec{
		Name: "self",
	}
}

// Words makes a parser scanner
type Words struct {
	Words []string `if:"label=_"`
}

func (*Words) Compose() composer.Spec {
	return composer.Spec{
		Name: "words",
	}
}

var Slots = []interface{}{
	(*GrammarMaker)(nil),
	(*ScannerMaker)(nil),
}
var Slats = []composer.Composer{
	(*Action)(nil),
	(*Alias)(nil),
	(*AllOf)(nil),
	(*AnyOf)(nil),
	(*Directive)(nil),
	(*Grammar)(nil),
	(*Noun)(nil),
	(*Retarget)(nil),
	(*Reverse)(nil),
	(*Self)(nil),
	(*Words)(nil),
}
