package compact

import (
	"strings"
	"unicode"

	"git.sr.ht/~ionous/iffy/dl/composer"
)

// "Else if:from:and:do:else:"
type sigBuilder struct {
	out    strings.Builder
	labels int
}

func (b *sigBuilder) String() string {
	return b.out.String()
}

// lede is in break_case
func (b *sigBuilder) WriteLede(c composer.Spec) {
	// change autogenerated break_case into PascalCase
	l := c.Lede
	if len(l) == 0 {
		l = c.Name
	}
	writeBreak(&b.out, l, true)
}

// label is in break_case
func (b *sigBuilder) WriteLabel(s string) {
	// write non-anonymous labels
	if anon := s == "_"; !anon {
		// add space between the lede and the first non-anonymous label
		if b.labels == 0 {
			b.out.WriteRune(' ')
		}
		// change autogenerated break_case into camelCase
		writeBreak(&b.out, s, false)
	}
	// all labels ( even anonymous ones ) are terminated by colons
	b.out.WriteRune(':')
	b.labels++
}

func writeBreak(out *strings.Builder, s string, cap bool) {
	for _, r := range s {
		if r == '_' {
			cap = true
		} else {
			if cap {
				r = unicode.ToUpper(r)
				cap = false
			}
			out.WriteRune(r)
		}
	}
}
