// Code generated by capnpc-go. DO NOT EDIT.

package reader

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type Pos struct{ capnp.Struct }

// Pos_TypeID is the unique identifier for the type Pos.
const Pos_TypeID = 0xcc1cb4b2f2228a16

func NewPos(s *capnp.Segment) (Pos, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Pos{st}, err
}

func NewRootPos(s *capnp.Segment) (Pos, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Pos{st}, err
}

func ReadRootPos(msg *capnp.Message) (Pos, error) {
	root, err := msg.RootPtr()
	return Pos{root.Struct()}, err
}

func (s Pos) String() string {
	str, _ := text.Marshal(0xcc1cb4b2f2228a16, s.Struct)
	return str
}

func (s Pos) Source() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s Pos) HasSource() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s Pos) SourceBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s Pos) SetSource(v string) error {
	return s.Struct.SetText(0, v)
}

func (s Pos) Offset() (string, error) {
	p, err := s.Struct.Ptr(1)
	return p.Text(), err
}

func (s Pos) HasOffset() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s Pos) OffsetBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(1)
	return p.TextBytes(), err
}

func (s Pos) SetOffset(v string) error {
	return s.Struct.SetText(1, v)
}

// Pos_List is a list of Pos.
type Pos_List struct{ capnp.List }

// NewPos creates a new list of Pos.
func NewPos_List(s *capnp.Segment, sz int32) (Pos_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return Pos_List{l}, err
}

func (s Pos_List) At(i int) Pos { return Pos{s.List.Struct(i)} }

func (s Pos_List) Set(i int, v Pos) error { return s.List.SetStruct(i, v.Struct) }

func (s Pos_List) String() string {
	str, _ := text.MarshalList(0xcc1cb4b2f2228a16, s.List)
	return str
}

// Pos_Promise is a wrapper for a Pos promised by a client call.
type Pos_Promise struct{ *capnp.Pipeline }

func (p Pos_Promise) Struct() (Pos, error) {
	s, err := p.Pipeline.Struct()
	return Pos{s}, err
}

const schema_cc763cb346d64bd9 = "x\xda\x120r`\x12d\x8dg`\x08dae\xfb" +
	"/\xd6\xa5\xf4i\xd3\x16\x993\x0c\x82\xbc\x8c\xffoz" +
	"_s\xdblSv\x86\x81\x95\x89\x9d\x81AP\xb4K" +
	"P\x16DK\x9630\xfe/JMLI-\xd2K" +
	"fL,\xc8+\xb0\x0a\xc8/f`\x08`d\x0c\xe4" +
	"`fa``ad`\x10\xd4\xb4b`\x08Ta" +
	"f\x0c4`b\x14dd\x14a\x04\x09\xea\x82\x045" +
	"\x98\x19\x03M\x98\x18\xed\x8b\xf3K\x8b\x92S\x19y\x18" +
	"\x98\x18y\x18\x18\xed\xf3\xd3\xd2\x8aSK`\\@\x00" +
	"\x00\x00\xff\xffb{\x1e<"

func init() {
	schemas.Register(schema_cc763cb346d64bd9,
		0xcc1cb4b2f2228a16)
}
