package eph

import (
	"git.sr.ht/~ionous/tapestry/dl/literal"
	"git.sr.ht/~ionous/tapestry/imp/assert"
	"git.sr.ht/~ionous/tapestry/jsn"
	"git.sr.ht/~ionous/tapestry/jsn/cout"
	"github.com/ionous/errutil"
)

// database/sql like interface
type Writer interface {
	Write(q string, args ...interface{}) error
}

// implemented by individual commands
type Ephemera interface {
	// fix? remove catalog from the signature?
	Assemble(c *Catalog, d *Domain, at string) error
	Phase() assert.Phase
	// the command builder generates commands;
	// this reverse the direction and generates calls to the command builder.
	Weave(assert.Assertions) error
}

//go:generate stringer -type=Phase

type PhaseActions map[assert.Phase]PhaseAction

type PhaseAction struct {
	Flags PhaseFlags
	Do    func(d *Domain) (err error)
}

// wrapper for implementing Ephemera with free functions.
// its a shortcut to defining new ephemera structs for every last processing statement;
// which works because its all the same process space.
// could separate these out into commands for inter-process communication, logging, etc. if ever needed.
type PhaseFunction struct {
	OnPhase assert.Phase
	Do      func(assert.World, assert.Assertions) error
}

func (fn PhaseFunction) Phase() assert.Phase { return fn.OnPhase }

func (fn PhaseFunction) Weave(k assert.Assertions) (err error) {
	return k.Schedule(fn.OnPhase, fn.Do)
}

func (fn PhaseFunction) Assemble(c *Catalog, d *Domain, at string) (err error) {
	var writeEph WriterFun = func(op Ephemera) {
		d.QueueEphemera(at, op)
	}
	return fn.Do(c, NewCommandBuilder(writeEph))
}

type PhaseFlags struct {
	NoDuplicates bool
}

// shared generic marshal prog to text
func marshalout(cmd interface{}) (ret string, err error) {
	if cmd != nil {
		if m, ok := cmd.(jsn.Marshalee); !ok {
			err = errutil.Fmt("can only marshal autogenerated types (%T)", cmd)
		} else {
			ret, err = cout.Marshal(m, literal.CompactEncoder)
		}
	}
	return
}
