// Code generated by "stringer -type=topicType"; DO NOT EDIT.

package jess

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[undeterminedTopic-0]
	_ = x[otherTopic-1]
	_ = x[pronounReference-2]
	_ = x[nounTopic-3]
}

const _topicType_name = "undeterminedTopicotherTopicpronounReferencenounTopic"

var _topicType_index = [...]uint8{0, 17, 27, 43, 52}

func (i topicType) String() string {
	if i < 0 || i >= topicType(len(_topicType_index)-1) {
		return "topicType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _topicType_name[_topicType_index[i]:_topicType_index[i+1]]
}
