# Scripting commands to debug and test stories.
Spec:requires:contains:
  - "debug"
  - "idl/rtti"
  - - # A runtime command that does... nothing.
      # ( Can be used to fill in branches ( ex. of if statements )
      #  or rules which aren't supposed to do anything. )
      Flow:slots:
        - "do_nothing"
        - "execute"

    - # Evaluate a boolean command and ensure it returns true.
      Flow:slots:lede:terms:
        - "expect"
        - "execute"
        - "expect"
        - - # A description of the test.
            Term:name:type:optional:
              - "_"
              - "label"
              - "text"
              - true
          - # The boolean command. If the command returns false, the expectation will fail and the game will generate an error.
            Term:name:type:
              - "test"
              - "value"
              - "bool_eval"

    - # Examine the most recent game output, and generate an error unless it matches the specified text.
      Flow:slots:lede:terms:
        - "expect_text"
        - "execute"
        - "expect"
        - - # The expected line or lines.
            # If an expected line ends with ellipses "..."
            # then only the first part of the line has to match.
            #
            # For example, if the expectation was "Hello...",
            # then the output "Hello World!" would match.
            Term:type:
              - "text"
              - "text_eval"

    - # Process fake input as if the player had typed it themselves.
      # Fabricate only works while running tests, and does nothing during normal game play.
      # Multiple actions can be specified by separating them with semi-colons. For example:
      #   Fabricate input: "s; jump; look"
      Flow:slots:terms:
        - "fabricate"
        - "execute"
        - - # One or more actions to handle as if typed by the player.
            Term:name:type:
              - "input"
              - "text"
              - "text_eval"

    - # Print a value that might be useful during development.
      # It will be hidden from players in the final game.
      Flow:slots:lede:terms:
        - "log_value"
        - "execute"
        - "log"
        - - # Importance of the message.
            Term:name:type:
              - "_"
              - "log_level"
              - "logging_level"
          - # Some text, or any other value, to display.
            Term:type:
              - "value"
              - "assignment"

    - # Used with [DebugLog].
      Str:options:
        - "logging_level"
        - - Option: "debug"
          - Option: "info"
          - Option: "warn"
          - Option: "error"

    - # Print a message that might be useful during development.
      # It will be hidden from players in the final game.
      Flow:slots:terms:
        - "note"
        - "execute"
        - - # One or more lines of text documentation.
            Term:name:type:
              - "_"
              - "text"
              - "text_eval"
          # Control the logging level. Defaults to debug.
          - Term:name:type:optional:
              - "level"
              - "log_level"
              - "logging_level"
              - true
