# Low level communication with a game server.
# None of these commands are available for use in game scripts.
Spec:requires:contains:
  - "frame"
  - "idl/prim"
  - - # The results of a a player initiated turn, or other client to server query.
      Flow:terms:
        - "frame"
        - - # The result of a query assignment sent to the server.
            Term:type:
              - "result"
              - "text"
          - # Changes as a result of a player's turn or a client query.
            Term:type:repeats:
              - "events"
              - "notification"
              - true
          - # Any critical server errors.
            # Returned to the client as a string
            # so that it can be displayed to the player.
            Term:type:optional:
              - "error"
              - "text"
              - true
    - # Marker interface used by all frame events.
      Slot: "notification"

    - # Printed text that should be visible the player.
      Flow:slots:terms:
        - "frame_output"
        - "notification"
        - - # The text to show to the player.
            Term:name:
              - "_"
              - "text"

    - # One or more scenes ( aka. domain ) have started.
      Flow:slots:terms:
        - "scene_started"
        - "notification"
        - - # The names of the scenes.
            Term:name:type:repeats:
              - "_"
              - "domains"
              - "text"
              - true
    - # One or more scenes ( aka. domain ) have finished.
      Flow:slots:terms:
        - "scene_ended"
        - "notification"
        - - # The names of the scenes.
            Term:name:type:repeats:
              - "_"
              - "domains"
              - "text"
              - true

    - # Some object in the game has changed from one state to another.
      Flow:slots:terms:
        - "state_changed"
        - "notification"
        - - # The object who's state has changed.
            Term:type:
              - "noun"
              - "text"
          - # The name of the set of states involved.
            Term:type:
              - "aspect"
              - "text"
          - # The name of the old state.
            Term:type:
              - "prev"
              - "text"
          - # The name of the new state.
            Term:type:
              - "trait"
              - "text"

    - # The relationship between two objects has changed. For instance, an object's whereabouts as indicated by a parent-child type relation.
      Flow:slots:terms:
        - "pair_changed"
        - "notification"
        - - # The id of the primary object.
            Term:type:
              - "a"
              - "text"
          - # The id of the secondary object.
            Term:type:
              - "b"
              - "text"
          - # The name of the relation in question.
            Term:type:
              - "rel"
              - "text"
