# System commands to manage a running game ( save, load, etc ).
Spec:requires:contains:
  - "game"
  - "idl/rtti"
  - - # Immediately end the current game.
      Flow:slots:
        - "quit_game"
        - "execute"
    - # Save the game.
      Flow:slots:
        - "save_game"
        - "execute"
    - # Load the most recent save.
      Flow:slots:
        - "load_game"
        - "execute"
    - # Unimplemented: rewind the game to undo the player's most recent input.
      Flow:slots:
        - "undo_turn"
        - "execute"
    - # Print the version of the tap executable.
      Flow:slots:
        - "print_version"
        - "execute"
