# Supply constant values to runtime evaluations.
# ( ie. a specific number when a [NumEval] is required. )
#
# Tell files support "shortcuts" which turn primitive values into literal commands. For instance, the number '5' in a .tell file is automatically transformed into the command "Num value: 5" whenever that's needed. Therefore, these commands are mainly for internal representation ( and for the blockly editor. )
Spec:requires:contains:
  - "literal"
  - - "idl/prim"
    - "idl/rtti"
  - - # A slot to identify constant values.
      Slot: "literal_value"
      blockly-color: "MATH_HUE"

    - # Specify an explicit true or false.
      Flow:slots:lede:terms:
        - "bool_value"
        - - "bool_eval"
          - "literal_value"
        - "bool"
        - - # The true or false value.
            Term:name:type:
              - "_"
              - "value"
              - "bool"

    - # Specify a particular number.
      Flow:slots:lede:terms:
        - "num_value"
        - - "num_eval"
          - "literal_value"
        - "num"
        - - # A literal number.
            Term:name:type:
              - "_"
              - "value"
              - "num"

    - # Specify a list of literal numbers.
      Flow:slots:lede:terms:
        - "num_list"
        - - "num_list_eval"
          - "literal_value"
        - "num"
        - - # Zero or more literal numbers.
            Term:name:type:repeats:
              - "list"
              - "values"
              - "num"
              - true

    - # Specify some constant text.
      Flow:slots:lede:terms:
        - "text_value"
        - - "text_eval"
          - "literal_value"
        - "text"
        - - # Some literal text.
            Term:name:type:
              - "_"
              - "value"
              - "text"
          - # Optionally, when the text represents the name of an (existing) object,
            # the kind of the object in question.
            Term:type:optional:
              - "kind"
              - "text"
              - true

    - # Specify a list of literal text values.
      Flow:slots:lede:terms:
        - "text_list"
        - - "text_list_eval"
          - "literal_value"
        - "text"
        - - # Zero or more text literals.
            Term:name:type:repeats:
              - "list"
              - "values"
              - "text"
              - true
          - # Optionally, when the text represents the names of (existing) objects,
            # the kind of the objects in question.
            Term:type:optional:
              - "kind"
              - "text"
              - true

    - # Specify a record composed of literal values.
      Flow:slots:lede:terms:
        - "record_value"
        - - "record_eval"
          - "literal_value"
        - "record"
        - - # The kind of the record being constructed.
            # All kinds must be pre-declared ( ex. via [DefineKind] or via jess. )
            Term:name:type:
              - "_"
              - "kind"
              - "text"
          - # A set of literal values for the fields of the record.
            # Any fields of the record which are not specified here,
            # are "zero initialized."
            Term:type:repeats:
              - "fields"
              - "field_value"
              - true
          - Term:type:private:
              - "cache"
              - "record_cache"
              - true

    - # Specify a series of records, all of the same kind.
      Flow:slots:lede:terms:
        - "record_list"
        - - "record_list_eval"
          - "literal_value"
        - "record"
        - - # The kind of the records being constructed.
            # All of the records in the list must be of the same kind.
            # All kinds must be pre-declared ( ex. via [DefineKind] or via jess. )
            Term:name:type:
              - "_"
              - "kind"
              - "text"
          - # Zero or more record literals.
            Term:name:type:repeats:
              - "list"
              - "records"
              - "field_list"
              - true
          - Term:type:private:
              - "cache"
              - "records_cache"
              - true

    - # A series of values used to build a record.
      Flow:slots:lede:terms:
        - "field_list"
        - "literal_value"
        - "field_list"
        - - # A set of literal values for the fields of the record.
            # Any fields of the record which are not specified here,
            # are "zero initialized."
            Term:name:type:repeats:
              - "_"
              - "fields"
              - "field_value"
              - true

    - # The name and value of a field used for initializing a literal record.
      Flow:lede:terms:
        - "field_value"
        - "field"
        - - # The name of a field in a record to initialize.
            # New field names cannot be added to records at runtime;
            # the field names must be part of the original declaration of the kind.
            Term:name:type:
              - "_"
              - "field"
              - "text"
          - # The literal value of the field.
            # The type of value must match the original declaration of the field.
            # ( ex. If the field was declared as a number, only a number can be used to initialize it. )
            Term:type:
              - "value"
              - "literal_value"
