# Boolean operations and loop handling.
Spec:requires:contains:
  - "logic"
  - - "idl/prim"
    - "idl/rtti"
  - - # This always returns true.
      Flow:slots:
        - "always"
        - "bool_eval"

    - # This always returns false.
      Flow:slots:
        - "never"
        - "bool_eval"

    - # Determine the "truthiness" of a value.
      # Bool values simply return their value.
      # Num values: are true when not exactly zero.
      # Text values: are true whenever they contain content.
      # List values: are true whenever the list is non-empty.
      # ( note this is similar to python, and different than javascript. )
      # Record values: are true whenever they have been initialized.
      # ( only sub-records start uninitialized; record variables are always true. )
      Flow:slots:lede:terms:
        - "is_value"
        - "bool_eval"
        - "is"
        - - # The value to test.
            Term:type:
              - "value"
              - "assignment"

    - # Check that every condition in a set of conditions returns true.
      # Stops after finding a failed condition.
      # An empty list returns false.
      Flow:slots:lede:terms:
        - "is_all"
        - "bool_eval"
        - "is"
        - - # One or more conditions to check for success.
            Term:name:type:repeats:
              - "all"
              - "test"
              - "bool_eval"
              - true

    - # Check whether any condition in a set of conditions returns true.
      # Stops after finding the first successful condition.
      # An empty list returns false.
      Flow:slots:lede:terms:
        - "is_any"
        - "bool_eval"
        - "is"
        - - # One or more conditions to check for success.
            Term:name:type:repeats:
              - "any"
              - "test"
              - "bool_eval"
              - true

    - # Determine the opposite of a condition.
      Flow:slots:terms:
        - "not"
        - "bool_eval"
        - - # The condition to check.
            Term:name:type:
              - "_"
              - "test"
              - "bool_eval"

    - # Determine the "falsiness" of a value.
      # This is the opposite of [TrueValue].
      Flow:slots:lede:terms:
        - "not_value"
        - "bool_eval"
        - "not"
        - - # The value to test.
            Term:type:
              - "value"
              - "assignment"

    - # Check that every condition in a set of conditions returns false.
      # Stops after finding any successful condition.
      # An empty list returns false.
      Flow:slots:lede:terms:
        - "not_all"
        - "bool_eval"
        - "not"
        - - # One or more conditions to check for failure.
            Term:name:type:repeats:
              - "all"
              - "test"
              - "bool_eval"
              - true

    - # Check whether any condition in a set of conditions returns false.
      # Stops after finding any failed condition.
      # An empty list returns false.
      Flow:slots:lede:terms:
        - "not_any"
        - "bool_eval"
        - "not"
        - - # One or more conditions to check for failure.
            Term:name:type:repeats:
              - "any"
              - "test"
              - "bool_eval"
              - true

    - # Helper for the else statements of [ChooseBranch].
      Slot: "brancher"

    - # Select a block of statements to run based on a true/false check.
      Flow:slots:lede:terms:
        - "choose_branch"
        - - "execute"
          - "brancher"
        - "if"
        - - # The condition to test.
            Term:name:type:
              - "_"
              - "condition"
              - "bool_eval"
          - # A set of local variables available while testing the condition and while running the do/else statements. These are initialized before testing the condition.
            Term:name:type:optional:repeats:
              - "assuming"
              - "args"
              - "arg"
              - true
              - true
          - # Statements which run when the condition succeeded.
            Term:name:type:repeats:
              - "do"
              - "exe"
              - "execute"
              - true
          - # An optional set of statements to evaluate when the condition failed.
            Term:type:optional:
              - "else"
              - "brancher"
              - true

    - # Run a set of statements after a condition has failed.
      Flow:slots:lede:terms:
        - "choose_nothing_else"
        - "brancher"
        - "finally"
        - - # One or more statements to run.
            Term:name:type:repeats:
              - "do"
              - "exe"
              - "execute"
              - true

    - # Pick one of two possible text values based on a condition.
      # ( This acts similar to a ternary. )
      Flow:slots:lede:terms:
        - "choose_num"
        - "num_eval"
        - "num"
        - - # The condition to test.
            Term:type:
              - "if"
              - "bool_eval"
          - # A set of local variables available while testing the condition and while running the do/else statements. These are initialized before testing the condition.
            Term:name:type:optional:repeats:
              - "assuming"
              - "args"
              - "arg"
              - true
              - true
          - # The number to use if the condition succeeds.
            # ( The eval is only processed if the condition succeeded. )
            Term:name:type:
              - "then"
              - "true"
              - "num_eval"
          - # The number to use if the condition fails.
            # ( The eval is only processed if the condition failed. )
            Term:name:type:optional:
              - "else"
              - "false"
              - "num_eval"
              - true

    - # Pick one of two possible text values based on a condition.
      # ( This acts similar to a ternary. )
      Flow:slots:lede:terms:
        - "choose_text"
        - "text_eval"
        - "text"
        - - # The condition to test.
            Term:type:
              - "if"
              - "bool_eval"
          - # A set of local variables available while testing the condition and while running the do/else statements. These are initialized before testing the condition.
            Term:name:type:optional:repeats:
              - "assuming"
              - "args"
              - "arg"
              - true
              - true
          - # The text to use if the condition succeeds.
            # ( The eval is only processed if the condition succeeded. )
            Term:name:type:
              - "then"
              - "true"
              - "text_eval"
          - # The text to use if the condition fails.
            # ( The eval is only processed if the condition failed. )
            Term:name:type:optional:
              - "else"
              - "false"
              - "text_eval"
              - true

    - # In a repeating loop, exit the loop;
      # or, in a rule, stop processing rules.
      Flow:slots:
        - "break"
        - "execute"

    - # In a repeating loop, try the next iteration of the loop;
      # or, in a rule, continue to the next rule.
      Flow:slots:
        - "continue"
        - "execute"

    - # Keep running a series of actions while a condition succeeds.
      Flow:slots:terms:
        - "repeat"
        - "execute"
        - - # The condition to check before running the loop.
            # If it succeeds, execute the loop;
            # if it fails, stop executing the loop.
            Term:name:type:
              - "if"
              - "condition"
              - "bool_eval"
          - # A set of variables available to the loop;
            # evaluated just once, before the loop's first run.
            Term:name:type:optional:repeats:
              - "initially"
              - "initial"
              - "arg"
              - true
              - true
          - # A set of variables available to the loop;
            # evaluated before each iteration of the loop.
            # ( These take precedence over the initial variables.
            # If the same names appear in both sets of variables, the ones here win. )
            Term:name:type:optional:repeats:
              - "assuming"
              - "args"
              - "arg"
              - true
              - true
          - # The statements to execute every loop.
            Term:name:type:repeats:
              - "do"
              - "exe"
              - "execute"
              - true
