# Low level communication between a game console and a running game.
# None of these commands are available for use in game scripts.
Spec:requires:contains:
  - "play"
  - "idl/prim"
  - - # a client-server message for the play app
      Slot: "play_message"
    - # a log message that can optionally be displayed to the client.
      Flow:slots:lede:terms:
        - "play_log"
        - "play_message"
        - "play"
        - - Term:type:
              - "log"
              - "text"
    - # app level change in state.
      Flow:slots:lede:terms:
        - "play_mode"
        - "play_message"
        - "play"
        - - Term:type:
              - "mode"
              - "play_modes"
    - # enum for play play_mode
      Str:options:
        - "play_modes"
        - - Option: "asm"
          - Option: "play"
          - Option: "complete"
          - Option: "error"
    - # output from the game itself.
      Flow:slots:lede:terms:
        - "play_out"
        - "play_message"
        - "play"
        - - Term:type:
              - "out"
              - "text"
