# Low level communication between a game console and a running game.
# None of these commands are available for use in game scripts.
Spec:requires:contains:
  - "play"
  - "idl/prim"
  - - # A client-server message for the play app.
      Slot: "play_message"
    - # A log message that might be displayed to the client for debugging.
      Flow:slots:lede:terms:
        - "play_log"
        - "play_message"
        - "play"
        - - Term:type:
              - "log"
              - "text"
    - # An app level change in state.
      Flow:slots:lede:terms:
        - "play_mode"
        - "play_message"
        - "play"
        - - Term:type:
              - "mode"
              - "play_modes"
    - # One of the app level states communicated by [PlayMode].
      Str:options:
        - "play_modes"
        - - Option: "asm"
          - Option: "play"
          - Option: "complete"
          - Option: "error"
    - # Text that should be displayed to the player.
      Flow:slots:lede:terms:
        - "play_out"
        - "play_message"
        - "play"
        - - Term:type:
              - "out"
              - "text"
