# Common type definitions.
Spec:contains:
  - "prim"
  - - # A true or false value.
      # Even though the definition here uses a string,
      # the tell loading code ( and the go generated code )
      # have shortcuts which understand how to handle unquoted ( literal ) values.
      Str:options:
        - "bool"
        - - Option: "false"
          - Option: "true"

    - # A sequence of characters of any length spanning multiple lines. See also: text.
      Str: "lines"

    - # An integer or floating point value.
      Num: "num"

    - # A sequence of characters of any length, all on one line. See also: lines.
      Str: "text"
