# Interrogate and manipulate object relationships at runtime.
Spec:contains:
  - "rel"
  - - # Return the relative of a noun.
      # For example: the right-hand noun in a one-to-one pairing.
      Flow:slots:lede:terms:
        - "relative_of"
        - "text_eval"
        - "relative"
        - - # Name of the relation in question.
            Term:name:type:
              - "_"
              - "relation_name"
              - "text_eval"
          - # Name of the left-side noun.
            Term:name:type:
              - "object"
              - "noun_name"
              - "text_eval"

    - # Return the relatives of a noun as a list of names.
      # For example: the right-hand nouns in a set of one-to-many pairing.
      Flow:slots:lede:terms:
        - "relatives_of"
        - "text_list_eval"
        - "relatives"
        - - # Name of the relation in question.
            Term:name:type:
              - "_"
              - "relation_name"
              - "text_eval"
          - # Name of the left-side noun.
            Term:name:type:
              - "object"
              - "noun_name"
              - "text_eval"

    - # Return the implied relative of a noun.
      # For example: the left-hand noun in a one-to-many relation.
      Flow:slots:lede:terms:
        - "reciprocal_of"
        - "text_eval"
        - "reciprocal"
        - - # Name of the relation in question.
            Term:name:type:
              - "_"
              - "relation_name"
              - "text_eval"
          - # Name of the right-side noun.
            Term:name:type:
              - "object"
              - "noun_name"
              - "text_eval"

    - # Return the implied relatives of a noun.
      # For example: the left-hand nouns in a set of one-to-many pairing.
      Flow:slots:lede:terms:
        - "reciprocals_of"
        - "text_list_eval"
        - "reciprocals"
        - - # Name of the relation in question.
            Term:name:type:
              - "_"
              - "relation_name"
              - "text_eval"
          - # Name of the right-side noun.
            Term:name:type:
              - "object"
              - "noun_name"
              - "text_eval"

    - # Relate two nouns.
      # Removes any previous pairings that might conflict with this one.
      Flow:slots:terms:
        - "relate"
        - "execute"
        - - # Name of the left-hand noun in the new pairing.
            Term:name:type:
              - "_"
              - "noun_name"
              - "text_eval"
          - # Name of the right-hand noun in the new pairing.
            Term:name:type:
              - "to"
              - "other_noun_name"
              - "text_eval"
          - # Name of the relation in question.
            Term:name:type:
              - "via"
              - "relation_name"
              - "text_eval"
