# Text template rendering.
# ( everything is "internal" because text templates generate the commands;
#  nothing is exposed for authors. )
Spec:requires:contains:
  - "render"
  - - "idl/call"
    - "idl/prim"
    - "idl/rtti"
  - - # Handles changing a template like {.boombip} into text.
      # If the name is a variable containing an object name: return the printed object name ( via "print name" );
      # if the name is a variable with some other text: return that text;
      # if the name isn't a variable but refers to some object: return that object's printed object name;
      # otherwise, its an error.
      internal: true
      Flow:slots:terms:
        - "render_name"
        - "text_eval"
        - - Term:name:type:
              - "_"
              - "name"
              - "text"
    - # Used with render pattern for arguments of unknown type.
      internal: true
      Slot: "render_eval"

    - # Pull a value from name that might refer either to a variable, or to an object.
      # This gets used by text templates when processing names.
      # The templates don't attempt to determine which names are objects and which names are variables.
      # For instance:
      #   - Say: "{.story.title} by {.story.author}"
      # uses UnknownDot for accessing "story".
      internal: true
      Flow:slots:lede:terms:
        - "unknown_dot"
        - - "bool_eval"
          - "num_eval"
          - "text_eval"
          - "record_eval"
          - "num_list_eval"
          - "text_list_eval"
          - "record_list_eval"
          - "render_eval"
        - "unknown"
        - - Term:name:type:
              - "_"
              - "name"
              - "text_eval"
          - Term:optional:repeats:
              - "dot"
              - true
              - true

    - # Pull a value from an assignment of unknown affinity.
      internal: true
      Flow:slots:terms:
        - "render_value"
        - "render_eval"
        - - Term:name:type:
              - "_"
              - "value"
              - "assignment"

    - # A version of core's call pattern
      # that figures out how to evaluate its arguments at runtime.
      internal: true
      Flow:slots:lede:terms:
        - "render_pattern"
        - - "bool_eval"
          - "text_eval"
          - "render_eval"
        - "render"
        - - Term:name:type:
              - "_"
              - "pattern_name"
              - "text"
          - Term:type:repeats:
              - "render"
              - "render_eval"
              - true

    - # Generate text in a replaceable manner.
      internal: true
      Flow:slots:terms:
        - "render_response"
        - - "execute"
          - "text_eval"
        - - Term:name:type:
              - "_"
              - "name"
              - "text"
          - Term:type:optional:
              - "text"
              - "text_eval"
              - true
