# Slots used to produce and consume values.
Spec:contains:
  - "rtti"
  - - # Identifies an object field, local variable, or pattern parameter. Addresses can be read from or written to.
      Slot: "address"

    - # Provides access to values in a generic way.
      # For example, when the type of a value isn't known in advance.
      # See also package assign. ( ex. [assign.FromBool] )
      Slot: "assignment"

    - # Commands which return true/false values.
      Slot: "bool_eval"
      blockly-color: "LOGIC_HUE"

    - # Commands which don't return a value.
      Slot: "execute"
      blockly-color: "PROCEDURES_HUE"
      blockly-stack: true

    - # Commands which return a list of numbers.
      Slot: "num_list_eval"
      blockly-color: "MATH_HUE"

    - # Commands which return a number.
      Slot: "num_eval"
      blockly-color: "MATH_HUE"

    - # Commands which return text.
      Slot: "text_eval"
      blockly-color: "TEXTS_HUE"

    - # Commands which return a list of text.
      Slot: "text_list_eval"
      blockly-color: "TEXTS_HUE"

    - # Commands which return a record.
      Slot: "record_eval"
      blockly-color: "LISTS_HUE"

    - # Commands which return a list of records.
      Slot: "record_list_eval"
      blockly-color: "LISTS_HUE"
