# Text manipulation and transformation.
Spec:requires:contains:
  - "text"
  - - "idl/prim"
    - "idl/rtti"
  - - # Count the number of characters in some text.
      Flow:slots:lede:terms:
        - "text_len"
        - "num_eval"
        - "text"
        - - # The text to measure.
            Term:name:type:
              - "length"
              - "text"
              - "text_eval"

    - # Determine whether one piece of text contains a second piece of text.
      #
      # The [rt.NumEval] version returns the first index at which the text appears,
      # or zero if not found.
      Flow:slots:lede:terms:
        - "find_text"
        - ["bool_eval", "num_eval"]
        - "find"
        - - # The text to search within.
            Term:name:type:
              - "_"
              - "text"
              - "text_eval"
          - # The text to find.
            Term:name:type:
              - "text"
              - "subtext"
              - "text_eval"

    - # Determine whether text starts in a particular way.
      Flow:slots:lede:terms:
        - "text_starts_with"
        - "bool_eval"
        - "is"
        - - # The text to search within.
            Term:name:type:
              - "text"
              - "text"
              - "text_eval"
          - # The text to find.
            Term:name:type:
              - "prefix"
              - "subtext"
              - "text_eval"

    - # Determine whether text ends in a particular way.
      Flow:slots:lede:terms:
        - "text_ends_with"
        - "bool_eval"
        - "is"
        - - # The text to search within.
            Term:name:type:
              - "text"
              - "text"
              - "text_eval"
          - # The text to find.
            Term:name:type:
              - "suffix"
              - "subtext"
              - "text_eval"

    - # Determine whether text is completely without content.
      # Even spaces are considered content.
      # The text "" is considered nothing,
      # The text " " is considered something.
      Flow:slots:lede:terms:
        - "is_nothing"
        - "bool_eval"
        - "is"
        - - # The text to check for content.
            Term:name:type:
              - "nothing"
              - "text"
              - "text_eval"

    - # Determine whether text matches a regular expression.
      # The expressions used are defined by go.
      # https://pkg.go.dev/regexp/syntax
      # https://github.com/google/re2/wiki/Syntax
      Flow:slots:lede:terms:
        - "matches"
        - "bool_eval"
        - "is"
        - - # The text to match the expression against.
            Term:name:type:
              - "text"
              - "text"
              - "text_eval"
          - # The expression to match against the text.
            Term:name:type:
              - "expression"
              - "match"
              - "text"
          - Term:type:private:
              - "cache"
              - "match_cache"
              - true

    - # Copy some text, changing its first letter to uppercase.
      Flow:slots:terms:
        - "capitalize"
        - "text_eval"
        - - # The text to copy, then capitalize.
            Term:name:type:
              - "_"
              - "text"
              - "text_eval"

    - # Combine text to produce new text.
      Flow:slots:terms:
        - "join"
        - "text_eval"
        - - # Optionally, a separator to put between each piece of text.
            Term:name:type:optional:
              - "_"
              - "sep"
              - "text_eval"
              - true
          - # The pieces of text to combine.
            Term:type:repeats:
              - "parts"
              - "text_eval"
              - true

    - # Copy some text, changing every letter into lowercase.
      # For example, turns "QUIET" into "quiet.
      Flow:slots:lede:terms:
        - "make_lowercase"
        - "text_eval"
        - "lower"
        - - # The text to copy, then lowercase.
            Term:name:type:
              - "_"
              - "text"
              - "text_eval"

    - # Copy some text with its contents flipped back to front.
      # For example, turns "Tapestry" into 'yrtsepaT'.
      Flow:slots:lede:terms:
        - "make_reversed"
        - "text_eval"
        - "reverse"
        - - # The text to copy and then reverse.
            Term:type:
              - "text"
              - "text_eval"

    - # Copy text, changing the start of each sentence so that it starts with a capital letter. ( Currently, "sentences" are considered to be a series of characters ending with a full-stop followed by a space. )
      # For example, "see the doctor run. run doctor. run." into "See the doctor run. Run doctor. Run."
      Flow:slots:lede:terms:
        - "make_sentence_case"
        - "text_eval"
        - "sentence"
        - - # The text to copy and then transform.
            Term:name:type:
              - "_"
              - "text"
              - "text_eval"

    - # Copy some text, making every word start with a capital letter.
      # For example, turns "empire apple" into "Empire Apple".
      Flow:slots:lede:terms:
        - "make_title_case"
        - "text_eval"
        - "title"
        - - # The text to copy and then transform.
            Term:name:type:
              - "_"
              - "text"
              - "text_eval"

    - # Copy some text, changing every letter into uppercase.
      # For example, transforms "loud" into "LOUD".
      Flow:slots:lede:terms:
        - "make_uppercase"
        - "text_eval"
        - "upper"
        - - # The text to copy and then transform into uppercase.
            Term:name:type:
              - "_"
              - "text"
              - "text_eval"

    - # Pluralize a word.
      # The singular form of a word can have more than one plural form.
      # For example: "person" can be "people" or "persons".
      # If more than one exists, this chooses arbitrarily.
      #
      # Note, The transformation uses predefined rules and some explicit mappings.
      # The story command [DefinePlural] can add new mappings.
      Flow:slots:lede:terms:
        - "pluralize"
        - "text_eval"
        - "plural"
        - - # The text to pluralize.
            Term:name:type:
              - "of"
              - "text"
              - "text_eval"

    - # Change a plural word into its singular form.
      # A plural word only has one singular form.
      # For example, given the word "people", return "person".
      # See [pluralize] for more information.
      Flow:slots:lede:terms:
        - "singularize"
        - "text_eval"
        - "singular"
        - - # The text to turn into its singular form.
            Term:name:type:
              - "of"
              - "text"
              - "text_eval"
