// Code generated by "stringer -type=options"; DO NOT EDIT.

package cmdxform

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stem-0]
	_ = x[plural-1]
	_ = x[singular-2]
	_ = x[normal-3]
}

const _options_name = "stempluralsingularnormal"

var _options_index = [...]uint8{0, 4, 10, 18, 24}

func (i options) String() string {
	if i < 0 || i >= options(len(_options_index)-1) {
		return "options(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _options_name[_options_index[i]:_options_index[i+1]]
}
