// Code generated by "stringer -type=Phase"; DO NOT EDIT.

package weave

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RequireDependencies-1]
	_ = x[RequirePlurals-2]
	_ = x[RequireAncestry-3]
	_ = x[RequirePatterns-4]
	_ = x[RequireDefaults-5]
	_ = x[RequireNouns-6]
	_ = x[RequireNames-7]
	_ = x[RequireRules-8]
	_ = x[RequireAll-9]
}

const _Phase_name = "RequireDependenciesRequirePluralsRequireAncestryRequirePatternsRequireDefaultsRequireNounsRequireNamesRequireRulesRequireAll"

var _Phase_index = [...]uint8{0, 19, 33, 48, 63, 78, 90, 102, 114, 124}

func (i Phase) String() string {
	i -= 1
	if i < 0 || i >= Phase(len(_Phase_index)-1) {
		return "Phase(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Phase_name[_Phase_index[i]:_Phase_index[i+1]]
}
