// Code generated by "stringer -type=Phase"; DO NOT EDIT.

package weaver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AnyPhase-0]
	_ = x[LanguagePhase-1]
	_ = x[AncestryPhase-2]
	_ = x[PropertyPhase-3]
	_ = x[NounPhase-4]
	_ = x[VerbPhase-5]
	_ = x[ConnectionPhase-6]
	_ = x[FallbackPhase-7]
	_ = x[ValuePhase-8]
	_ = x[NextPhase-9]
	_ = x[NumPhases-10]
}

const _Phase_name = "AnyPhaseLanguagePhaseAncestryPhasePropertyPhaseNounPhaseVerbPhaseConnectionPhaseFallbackPhaseValuePhaseNextPhaseNumPhases"

var _Phase_index = [...]uint8{0, 8, 21, 34, 47, 56, 65, 80, 93, 103, 112, 121}

func (i Phase) String() string {
	if i < 0 || i >= Phase(len(_Phase_index)-1) {
		return "Phase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Phase_name[_Phase_index[i]:_Phase_index[i+1]]
}
